export type ScenarioDefinition = {
  scenarioId: string;
  accountName: string;
  contactEmail: string;
  stripeCustomerId: string;
  posthogDistinctId: string;
  initialMrrCents: number;
  expectedRisk: boolean;
  expectedSeverity: 'low' | 'medium' | 'high' | 'critical';
  expectedAction: string;
  expectedResolution: string | null;
  expectedStrictRecoveredCents: number;
  expectedProtectedCents: number;
  contactPolicy?: 'allow' | 'do_not_contact';
  featuresPatch: Record<string, any>;
  notes: string;
};

export const SCENARIO_MANIFEST_V1: ScenarioDefinition[] = [
  {
    scenarioId: 'ALLEL-001',
    accountName: 'Vanguard Infra',
    contactEmail: 'kushagra@vanguardinfra.io',
    stripeCustomerId: 'cus_vanguard_001',
    posthogDistinctId: 'ph_kushagra_001',
    initialMrrCents: 50000,
    expectedRisk: false,
    expectedSeverity: 'low',
    expectedAction: 'no_action',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 50000,
      failedPaymentCount7d: 0,
      failedPaymentCount30d: 0,
      usageAvailable: true,
      usageCurrent7d: 120,
      usagePrevious7d: 115,
      usageDeltaPercent: 4.35,
      keyFeatureCurrent7d: 15,
      keyFeaturePrevious7d: 14,
      keyFeatureMissing: false,
    },
    notes: 'Stable healthy account. Active billing, consistent usage (Founder: Kushagra Singh).',
  },
  {
    scenarioId: 'ALLEL-002',
    accountName: 'Nexus Flow',
    contactEmail: 'rishi@nexusflow.ai',
    stripeCustomerId: 'cus_nexus_002',
    posthogDistinctId: 'ph_rishi_002',
    initialMrrCents: 90000,
    expectedRisk: false,
    expectedSeverity: 'low',
    expectedAction: 'no_action',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 90000,
      failedPaymentCount7d: 0,
      failedPaymentCount30d: 0,
      usageAvailable: true,
      usageCurrent7d: 250,
      usagePrevious7d: 180,
      usageDeltaPercent: 38.89,
      keyFeatureCurrent7d: 30,
      keyFeaturePrevious7d: 20,
      keyFeatureMissing: false,
    },
    notes: 'Growing healthy account. Positive delta must not trigger risk (Founder: Rishi Sharma).',
  },
  {
    scenarioId: 'ALLEL-003',
    accountName: 'Zenith Books',
    contactEmail: 'harsh@zenithbooks.co',
    stripeCustomerId: 'cus_zenith_003',
    posthogDistinctId: 'ph_harsh_003',
    initialMrrCents: 40000,
    expectedRisk: false,
    expectedSeverity: 'low',
    expectedAction: 'no_action',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 40000,
      failedPaymentCount7d: 0,
      failedPaymentCount30d: 0,
      usageAvailable: true,
      usageCurrent7d: 3,
      usagePrevious7d: 5,
      usageDeltaPercent: null, // Volume < 10 events
    },
    notes: 'Low volume usage. Delta unavailable, no volatile alert (Founder: Harsh Patel).',
  },
  {
    scenarioId: 'ALLEL-004',
    accountName: 'Aura Analytics',
    contactEmail: 'sharanya@auraanalytics.com',
    stripeCustomerId: 'cus_aura_004',
    posthogDistinctId: 'ph_sharanya_004',
    initialMrrCents: 120000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'billing_recovery_email',
    expectedResolution: 'strictly_recovered',
    expectedStrictRecoveredCents: 120000,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 120000,
      failedPaymentCount7d: 1,
      failedPaymentCount30d: 1,
      lastInvoiceId: 'in_aura_004',
      lastInvoiceStatus: 'open',
      usageAvailable: true,
      usageCurrent7d: 80,
      usagePrevious7d: 82,
      usageDeltaPercent: -2.44,
    },
    notes: 'Single payment failure triggers billing recovery draft (Founder: Sharanya Rao).',
  },
  {
    scenarioId: 'ALLEL-005',
    accountName: 'FintechScale',
    contactEmail: 'sameer@fintechscale.io',
    stripeCustomerId: 'cus_fintech_005',
    posthogDistinctId: 'ph_sameer_005',
    initialMrrCents: 200000,
    expectedRisk: true,
    expectedSeverity: 'critical',
    expectedAction: 'billing_recovery_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 200000,
      failedPaymentCount7d: 2,
      failedPaymentCount30d: 2,
      lastInvoiceId: 'in_fintech_005',
      lastInvoiceStatus: 'open',
      usageAvailable: true,
      usageCurrent7d: 150,
      usagePrevious7d: 155,
      usageDeltaPercent: -3.23,
    },
    notes: 'Two failures in 7 days trigger critical override (Founder: Sameer Verma).',
  },
  {
    scenarioId: 'ALLEL-006',
    accountName: 'GridPulse AI',
    contactEmail: 'samyak@gridpulse.io',
    stripeCustomerId: 'cus_pulse_006',
    posthogDistinctId: 'ph_samyak_006',
    initialMrrCents: 75000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'billing_recovery_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 75000,
      failedPaymentCount7d: 0,
      failedPaymentCount30d: 1,
      lastInvoiceId: 'in_pulse_006',
      usageAvailable: true,
      usageCurrent7d: 60,
      usagePrevious7d: 60,
      usageDeltaPercent: 0,
    },
    notes: 'Past due billing status with baseline preserved (Founder: Samyak Jain).',
  },
  {
    scenarioId: 'ALLEL-007',
    accountName: 'DataVibe',
    contactEmail: 'shaurya@datavibe.io',
    stripeCustomerId: 'cus_datavibe_007',
    posthogDistinctId: 'ph_shaurya_007',
    initialMrrCents: 150000,
    expectedRisk: true,
    expectedSeverity: 'critical',
    expectedAction: 'cancellation_rescue_email',
    expectedResolution: 'protected',
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 150000,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 150000,
      failedPaymentCount7d: 0,
      cancelIntentAt: new Date().toISOString(),
      usageAvailable: true,
      usageCurrent7d: 40,
      usagePrevious7d: 90,
      usageDeltaPercent: -55.56,
    },
    notes: 'Cancellation intent before lost billing. Reversal counts as protected (Founder: Shaurya Gupta).',
  },
  {
    scenarioId: 'ALLEL-008',
    accountName: 'Hyperion Dispatch',
    contactEmail: 'mayank@hyperiondispatch.com',
    stripeCustomerId: 'cus_hyperion_008',
    posthogDistinctId: 'ph_mayank_008',
    initialMrrCents: 300000,
    expectedRisk: true,
    expectedSeverity: 'critical',
    expectedAction: 'cancellation_rescue_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'cancelled',
      currentMrrCents: 0,
      preCancelMrrCents: 300000,
      cancelledAt: new Date().toISOString(),
      usageAvailable: true,
      usageCurrent7d: 10,
      usagePrevious7d: 80,
      usageDeltaPercent: -87.5,
    },
    notes: 'Cancelled subscription retains $3000 pre-cancel baseline (Founder: Mayank Agarwal).',
  },
  {
    scenarioId: 'ALLEL-009',
    accountName: 'Cobalt Core',
    contactEmail: 'ananya@cobaltcore.io',
    stripeCustomerId: 'cus_cobalt_009',
    posthogDistinctId: 'ph_ananya_009',
    initialMrrCents: 180000,
    expectedRisk: true,
    expectedSeverity: 'medium',
    expectedAction: 'monitor_only',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 180000,
      failedPaymentCount7d: 0,
      usageAvailable: true,
      usageCurrent7d: 70,
      usagePrevious7d: 100,
      usageDeltaPercent: -30.0,
      keyFeatureCurrent7d: 8,
      keyFeaturePrevious7d: 10,
      keyFeatureMissing: false,
    },
    notes: 'Moderate usage decline (-30%) creates medium severity / monitor (Founder: Ananya Iyer).',
  },
  {
    scenarioId: 'ALLEL-010',
    accountName: 'KryptonDB',
    contactEmail: 'kabir@kryptondb.org',
    stripeCustomerId: 'cus_krypton_010',
    posthogDistinctId: 'ph_kabir_010',
    initialMrrCents: 250000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'usage_checkin_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 250000,
      failedPaymentCount7d: 0,
      usageAvailable: true,
      usageCurrent7d: 25,
      usagePrevious7d: 100,
      usageDeltaPercent: -75.0,
    },
    notes: 'Severe usage decline (-75%) triggers usage checkin email (Founder: Kabir Mehta).',
  },
  {
    scenarioId: 'ALLEL-011',
    accountName: 'Vortex Data',
    contactEmail: 'tanvi@vortexdata.ai',
    stripeCustomerId: 'cus_vortex_011',
    posthogDistinctId: 'ph_tanvi_011',
    initialMrrCents: 400000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'usage_checkin_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 400000,
      failedPaymentCount7d: 0,
      usageAvailable: true,
      usageCurrent7d: 80,
      usagePrevious7d: 85,
      usageDeltaPercent: -5.88,
      keyFeatureCurrent7d: 0,
      keyFeaturePrevious7d: 6,
      keyFeatureMissing: true,
    },
    notes: 'Key feature disappearance triggers high usage component (Founder: Tanvi Saxena).',
  },
  {
    scenarioId: 'ALLEL-012',
    accountName: 'Apex MultiRail',
    contactEmail: 'rohan@apexmultirail.co',
    stripeCustomerId: 'cus_apex_012',
    posthogDistinctId: 'ph_rohan_012',
    initialMrrCents: 400000,
    expectedRisk: true,
    expectedSeverity: 'critical',
    expectedAction: 'compound_recovery_email',
    expectedResolution: 'strictly_recovered',
    expectedStrictRecoveredCents: 400000,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 400000,
      failedPaymentCount7d: 1,
      lastInvoiceId: 'in_apex_012',
      usageAvailable: true,
      usageCurrent7d: 35,
      usagePrevious7d: 100,
      usageDeltaPercent: -65.0,
    },
    notes: 'Payment failure + severe usage decline triggers critical compound action (Founder: Rohan Trivedi).',
  },
  {
    scenarioId: 'ALLEL-013',
    accountName: 'Beacon Shield',
    contactEmail: 'divya@beaconshield.com',
    stripeCustomerId: 'cus_beacon_013',
    posthogDistinctId: 'ph_divya_013',
    initialMrrCents: 100000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'no_action',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    contactPolicy: 'do_not_contact',
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 100000,
      failedPaymentCount7d: 1,
    },
    notes: 'Payment failure suppressed by explicit do-not-contact policy (Founder: Divya Nair).',
  },
  {
    scenarioId: 'ALLEL-014',
    accountName: 'Lattice Systems',
    contactEmail: 'aditya@latticesys.io',
    stripeCustomerId: 'cus_lattice_014',
    posthogDistinctId: 'ph_aditya_014',
    initialMrrCents: 150000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'founder_review',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 150000,
      failedPaymentCount7d: 1,
    },
    notes: 'Ambiguous identity triggers founder review instead of automated email (Founder: Aditya Joshi).',
  },
  {
    scenarioId: 'ALLEL-015',
    accountName: 'Prism Storefronts',
    contactEmail: 'neha@prismstorefronts.com',
    stripeCustomerId: 'cus_prism_015',
    posthogDistinctId: 'ph_neha_015',
    initialMrrCents: 130000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'billing_recovery_email',
    expectedResolution: 'engaged',
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 130000,
      failedPaymentCount7d: 1,
      lastInvoiceId: 'in_prism_015',
      usageAvailable: true,
      usageCurrent7d: 60,
      usagePrevious7d: 60,
      usageDeltaPercent: 0,
      communicationAvailable: true,
      lastOutboundAt: new Date(Date.now() - 48 * 3600000).toISOString(),
      lastInboundAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    },
    notes: 'Customer replied to email but invoice remains unpaid. Engaged = true, strict revenue = $0 (Founder: Neha Kulkarni).',
  },
];
