export type ScenarioDefinition = {
  scenarioId: string;
  accountName: string;
  contactEmail: string;
  stripeCustomerId: string;
  posthogDistinctId: string;
  initialMrrCents: number;
  expectedRisk: boolean;
  expectedSeverity: 'low' | 'medium' | 'high' | 'critical';
  expectedAction: string;
  expectedResolution: string | null;
  expectedStrictRecoveredCents: number;
  expectedProtectedCents: number;
  contactPolicy?: 'allow' | 'do_not_contact';
  featuresPatch: Record<string, any>;
  notes: string;
};

export const SCENARIO_MANIFEST_V1: ScenarioDefinition[] = [
  {
    scenarioId: 'ALLEL-001',
    accountName: 'Scenario 001 — Stable Control',
    contactEmail: 'scenario001@example.com',
    stripeCustomerId: 'cus_allel_001',
    posthogDistinctId: 'distinct_allel_001',
    initialMrrCents: 50000,
    expectedRisk: false,
    expectedSeverity: 'low',
    expectedAction: 'no_action',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 50000,
      failedPaymentCount7d: 0,
      failedPaymentCount30d: 0,
      usageAvailable: true,
      usageCurrent7d: 120,
      usagePrevious7d: 115,
      usageDeltaPercent: 4.35,
      keyFeatureCurrent7d: 15,
      keyFeaturePrevious7d: 14,
      keyFeatureMissing: false,
    },
    notes: 'Stable healthy account. Active billing, consistent usage.',
  },
  {
    scenarioId: 'ALLEL-002',
    accountName: 'Scenario 002 — Growing Control',
    contactEmail: 'scenario002@example.com',
    stripeCustomerId: 'cus_allel_002',
    posthogDistinctId: 'distinct_allel_002',
    initialMrrCents: 90000,
    expectedRisk: false,
    expectedSeverity: 'low',
    expectedAction: 'no_action',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 90000,
      failedPaymentCount7d: 0,
      failedPaymentCount30d: 0,
      usageAvailable: true,
      usageCurrent7d: 250,
      usagePrevious7d: 180,
      usageDeltaPercent: 38.89,
      keyFeatureCurrent7d: 30,
      keyFeaturePrevious7d: 20,
      keyFeatureMissing: false,
    },
    notes: 'Growing healthy account. Positive delta must not trigger risk.',
  },
  {
    scenarioId: 'ALLEL-003',
    accountName: 'Scenario 003 — Low-Volume Usage Edge',
    contactEmail: 'scenario003@example.com',
    stripeCustomerId: 'cus_allel_003',
    posthogDistinctId: 'distinct_allel_003',
    initialMrrCents: 40000,
    expectedRisk: false,
    expectedSeverity: 'low',
    expectedAction: 'no_action',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 40000,
      failedPaymentCount7d: 0,
      failedPaymentCount30d: 0,
      usageAvailable: true,
      usageCurrent7d: 3,
      usagePrevious7d: 5,
      usageDeltaPercent: null, // Volume < 10 events
    },
    notes: 'Low volume usage. Delta unavailable, no volatile alert.',
  },
  {
    scenarioId: 'ALLEL-004',
    accountName: 'Scenario 004 — Single Payment Failure',
    contactEmail: 'scenario004@example.com',
    stripeCustomerId: 'cus_allel_004',
    posthogDistinctId: 'distinct_allel_004',
    initialMrrCents: 120000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'billing_recovery_email',
    expectedResolution: 'strictly_recovered',
    expectedStrictRecoveredCents: 120000,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 120000,
      failedPaymentCount7d: 1,
      failedPaymentCount30d: 1,
      lastInvoiceId: 'in_allel_004',
      lastInvoiceStatus: 'open',
      usageAvailable: true,
      usageCurrent7d: 80,
      usagePrevious7d: 82,
      usageDeltaPercent: -2.44,
    },
    notes: 'Single payment failure triggers billing recovery draft.',
  },
  {
    scenarioId: 'ALLEL-005',
    accountName: 'Scenario 005 — Repeated Payment Failure',
    contactEmail: 'scenario005@example.com',
    stripeCustomerId: 'cus_allel_005',
    posthogDistinctId: 'distinct_allel_005',
    initialMrrCents: 200000,
    expectedRisk: true,
    expectedSeverity: 'critical',
    expectedAction: 'billing_recovery_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 200000,
      failedPaymentCount7d: 2,
      failedPaymentCount30d: 2,
      lastInvoiceId: 'in_allel_005',
      lastInvoiceStatus: 'open',
      usageAvailable: true,
      usageCurrent7d: 150,
      usagePrevious7d: 155,
      usageDeltaPercent: -3.23,
    },
    notes: 'Two failures in 7 days trigger critical override.',
  },
  {
    scenarioId: 'ALLEL-006',
    accountName: 'Scenario 006 — Past Due Subscription',
    contactEmail: 'scenario006@example.com',
    stripeCustomerId: 'cus_allel_006',
    posthogDistinctId: 'distinct_allel_006',
    initialMrrCents: 75000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'billing_recovery_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 75000,
      failedPaymentCount7d: 0,
      failedPaymentCount30d: 1,
      lastInvoiceId: 'in_allel_006',
      usageAvailable: true,
      usageCurrent7d: 60,
      usagePrevious7d: 60,
      usageDeltaPercent: 0,
    },
    notes: 'Past due billing status with baseline preserved.',
  },
  {
    scenarioId: 'ALLEL-007',
    accountName: 'Scenario 007 — Cancellation Intent',
    contactEmail: 'scenario007@example.com',
    stripeCustomerId: 'cus_allel_007',
    posthogDistinctId: 'distinct_allel_007',
    initialMrrCents: 150000,
    expectedRisk: true,
    expectedSeverity: 'critical',
    expectedAction: 'cancellation_rescue_email',
    expectedResolution: 'protected',
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 150000,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 150000,
      failedPaymentCount7d: 0,
      cancelIntentAt: new Date().toISOString(),
      usageAvailable: true,
      usageCurrent7d: 40,
      usagePrevious7d: 90,
      usageDeltaPercent: -55.56,
    },
    notes: 'Cancellation intent before lost billing. Reversal counts as protected.',
  },
  {
    scenarioId: 'ALLEL-008',
    accountName: 'Scenario 008 — Subscription Cancellation',
    contactEmail: 'scenario008@example.com',
    stripeCustomerId: 'cus_allel_008',
    posthogDistinctId: 'distinct_allel_008',
    initialMrrCents: 300000,
    expectedRisk: true,
    expectedSeverity: 'critical',
    expectedAction: 'cancellation_rescue_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'cancelled',
      currentMrrCents: 0,
      preCancelMrrCents: 300000,
      cancelledAt: new Date().toISOString(),
      usageAvailable: true,
      usageCurrent7d: 10,
      usagePrevious7d: 80,
      usageDeltaPercent: -87.5,
    },
    notes: 'Cancelled subscription retains $3000 pre-cancel baseline.',
  },
  {
    scenarioId: 'ALLEL-009',
    accountName: 'Scenario 009 — Moderate Usage Decline',
    contactEmail: 'scenario009@example.com',
    stripeCustomerId: 'cus_allel_009',
    posthogDistinctId: 'distinct_allel_009',
    initialMrrCents: 180000,
    expectedRisk: true,
    expectedSeverity: 'medium',
    expectedAction: 'monitor_only',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 180000,
      failedPaymentCount7d: 0,
      usageAvailable: true,
      usageCurrent7d: 70,
      usagePrevious7d: 100,
      usageDeltaPercent: -30.0,
      keyFeatureCurrent7d: 8,
      keyFeaturePrevious7d: 10,
      keyFeatureMissing: false,
    },
    notes: 'Moderate usage decline (-30%) creates medium severity / monitor.',
  },
  {
    scenarioId: 'ALLEL-010',
    accountName: 'Scenario 010 — Severe Usage Decline',
    contactEmail: 'scenario010@example.com',
    stripeCustomerId: 'cus_allel_010',
    posthogDistinctId: 'distinct_allel_010',
    initialMrrCents: 250000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'usage_checkin_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 250000,
      failedPaymentCount7d: 0,
      usageAvailable: true,
      usageCurrent7d: 25,
      usagePrevious7d: 100,
      usageDeltaPercent: -75.0,
    },
    notes: 'Severe usage decline (-75%) triggers usage checkin email.',
  },
  {
    scenarioId: 'ALLEL-011',
    accountName: 'Scenario 011 — Key Feature Disappearance',
    contactEmail: 'scenario011@example.com',
    stripeCustomerId: 'cus_allel_011',
    posthogDistinctId: 'distinct_allel_011',
    initialMrrCents: 400000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'usage_checkin_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'active',
      currentMrrCents: 400000,
      failedPaymentCount7d: 0,
      usageAvailable: true,
      usageCurrent7d: 80,
      usagePrevious7d: 85,
      usageDeltaPercent: -5.88,
      keyFeatureCurrent7d: 0,
      keyFeaturePrevious7d: 6,
      keyFeatureMissing: true,
    },
    notes: 'Key feature disappearance triggers high usage component.',
  },
  {
    scenarioId: 'ALLEL-012',
    accountName: 'Scenario 012 — Compound Billing and Usage',
    contactEmail: 'scenario012@example.com',
    stripeCustomerId: 'cus_allel_012',
    posthogDistinctId: 'distinct_allel_012',
    initialMrrCents: 350000,
    expectedRisk: true,
    expectedSeverity: 'critical',
    expectedAction: 'compound_recovery_email',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 350000,
      failedPaymentCount7d: 1,
      lastInvoiceId: 'in_allel_012',
      usageAvailable: true,
      usageCurrent7d: 35,
      usagePrevious7d: 100,
      usageDeltaPercent: -65.0,
    },
    notes: 'Payment failure + severe usage decline triggers critical compound action.',
  },
  {
    scenarioId: 'ALLEL-013',
    accountName: 'Scenario 013 — Do Not Contact Policy',
    contactEmail: 'scenario013@example.com',
    stripeCustomerId: 'cus_allel_013',
    posthogDistinctId: 'distinct_allel_013',
    initialMrrCents: 100000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'no_action',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    contactPolicy: 'do_not_contact',
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 100000,
      failedPaymentCount7d: 1,
    },
    notes: 'Payment failure suppressed by explicit do-not-contact policy.',
  },
  {
    scenarioId: 'ALLEL-014',
    accountName: 'Scenario 014 — Ambiguous Email Identity',
    contactEmail: 'scenario014@example.com',
    stripeCustomerId: 'cus_allel_014',
    posthogDistinctId: 'distinct_allel_014',
    initialMrrCents: 150000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'founder_review',
    expectedResolution: null,
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 150000,
      failedPaymentCount7d: 1,
    },
    notes: 'Ambiguous identity triggers founder review instead of automated email.',
  },
  {
    scenarioId: 'ALLEL-015',
    accountName: 'Scenario 015 — Reply Is Not Revenue',
    contactEmail: 'scenario015@example.com',
    stripeCustomerId: 'cus_allel_015',
    posthogDistinctId: 'distinct_allel_015',
    initialMrrCents: 120000,
    expectedRisk: true,
    expectedSeverity: 'high',
    expectedAction: 'billing_recovery_email',
    expectedResolution: 'engaged',
    expectedStrictRecoveredCents: 0,
    expectedProtectedCents: 0,
    featuresPatch: {
      billingAvailable: true,
      billingStatus: 'past_due',
      currentMrrCents: 120000,
      failedPaymentCount7d: 1,
      lastInvoiceId: 'in_allel_015',
      usageAvailable: true,
      usageCurrent7d: 60,
      usagePrevious7d: 60,
      usageDeltaPercent: 0,
      communicationAvailable: true,
      lastOutboundAt: new Date(Date.now() - 48 * 3600000).toISOString(),
      lastInboundAt: new Date(Date.now() - 24 * 3600000).toISOString(),
    },
    notes: 'Customer replied to email but invoice remains unpaid. Engaged = true, strict revenue = $0.',
  },
];
